language: node_js
node_js:
  - '6'
  - '5'
  - '4'
branches:
  only:
  - master
before script: 
  - npm install -g istanbul 
  - npm install -g codeclimate-test-reporter
script:
  - npm run buildtest
after_success:
  - CODECLIMATE_REPO_TOKEN=`echo $CODECLIMATE_REPO_TOKEN` codeclimate-test-reporter < ./coverage/lcov.info